version: 2
jobs:
    make_resume:
        docker:
          - image: jmoney8080/latex-resume-builder:0.0.5
        working_directory: ~/resume
        steps:
            - checkout
            - run:
                name: Make Resume
                command: make JonathanMonette_resume.pdf
    release_resume:
        docker:
          - image: jmoney8080/latex-resume-builder:0.0.5
        working_directory: ~/resume
        steps:
            - checkout
            - run:
                name: Make Release
                command: make release
workflows:
    version: 2
    commit-workflow:
        jobs:
            - make_resume:
                filters:
                    branches:
                        only: master
            - release_resume:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v\d+\.\d+\.\d+$/