version: 2

jobs:
    build:
        docker:
            - image: circleci/golang:1.8
        working_directory: ~/resume
        steps:
            - checkout
            - run:
                name: Update debian
                command: sudo apt-get update -y
            - run:
                name: Install luatex
                command: sudo apt-get install -y texlive-luatex
            - run:
                name: debug stuff
                command: find / -name "lualatex" -type f
            - run:
                name: Make Resume
                command: make JonathanMonette_resume.pdf
    publish-github-release:
        docker:
            - image: circleci/golang:1.8
        steps:
            - attach_workspace:
                at: ./
            - run:
                name: "Publish Release on GitHub"
                command: |
                    go get github.com/tcnksm/ghr
                    VERSION=$(git describe --abbrev=0)
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./JonathanMonette_resume.pdf
workflows:
    version: 2
    commit-workflow:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
            - publish-github-release:
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^\d+\.\d+\.\d+$/