version: 2
jobs:
    make_resume:
        docker:
          - image: jmoney8080/latex-resume-builder:0.0.3
        working_directory: ~/resume
        steps:
            - checkout
            - run:
                name: Make Resume
                command: make JonathanMonette_resume.pdf
workflows:
    version: 2
    commit-workflow:
        jobs:
            - make_resume:
                requires:
                    - build
                filters:
                    branches:
                        only: master